; PlatformIO Project Configuration File

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_type = debug
monitor_speed = 115200
upload_speed = 2000000
monitor_filters = default, esp32_exception_decoder, time
monitor_rts = 0
monitor_dtr = 0

build_flags = 
    -DBOARD_HAS_PSRAM
    ; -DARDUINO_ESP32S3_DEV
    ; -DCONFIG_SPIRAM=1
    ; -DCONFIG_SPIRAM_MODE_OCT=1
    ; -DCONFIG_ESP32S3_SPIRAM_SUPPORT=1
    ; -DCONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=131072
    ; -DCONFIG_SPIRAM_USE_CAPS_ALLOC=1
    ; -DSYNTH_DEBUG
    ; -DIQ_ADC_ENABLE

board_build.arduino.memory_type = qio_opi

lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.3
