; PlatformIO Project Configuration File

[env:esp32-s3-devkitc-1]
platform = espressif32
# to have ETH.h working with W5500, use a specific version of the framework, we need to specify it in platform_packages
platform_packages=
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.2
  framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.2/esp32-arduino-libs-3.0.2.zip

board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
framework = arduino
build_type = debug
monitor_speed = 115200
upload_speed = 2000000
monitor_filters = default, esp32_exception_decoder, time
monitor_rts = 0
monitor_dtr = 0
monitor_echo = 0


build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -DAM_TEST_MODE=1
    -DCORE_DEBUG_LEVEL=3 ; Livello 4 = Debug (o 5 per Verbose)
    -I${PROJECT_DIR}/lib/ft8_lib
    -I${PROJECT_DIR}/lib/ft8_lib/ft8_decode
    -I${PROJECT_DIR}/lib/ft8_lib/common
    -I${PROJECT_DIR}/lib/ft8_lib/fft
    -DFT8_MAX_CANDIDATES=40 ; 50 is the default, but 25 is usually sufficient and much faster on a microcontroller
    -DFT8_LDPC_ITERATIONS=10 ; 10 is the default, but 5 is usually sufficient and much faster on a microcontroller
    -DFT8_MAX_DECODED_MSGS=200

    
board_build.arduino.memory_type = qio_opi

board_build.filesystem = littlefs
board_build.partitions = mypartitions.csv

lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.3
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/guido57/ESP32_ft8_lib

# extra_scripts = pre:extra/add_ft8_sources.py
